---
# This role contains common plays that will run on all nodes

- name: ensure group yunion exists
  group:
    name: yunion
    state: present

- name: ensure user yunion exists
  user:
    name: yunion
    shell: /bin/bash
    groups: yunion

- name: make cache for centos x86
  shell: "yum makecache fast"
  args:
    warn: no
  when:
  - is_centos_based is defined

- name: make cache for debian like os
  shell: "apt-get update"
  args:
    warn: no
  when:
  - is_debian_based is defined

- name: init dirs
  shell: "mkdir -p /etc/docker"
  args:
    warn: no

- name: yum install yunion packages; it should take a few minutes...
  package: name="{{ item }}" state="present"
  with_items:
    - ansible
    - autogen-libopts
    - bash-completion
    - bridge-utils
    - ceph-common
    - conntrack-tools
    - container-selinux
    - containerd.io
    - cri-tools
    - docker-ce
    - epel-release
    - fuse
    - fuse-devel
    - fuse-libs
    - htop
    - ipvsadm
    - iscsi-initiator-utils
    - jq
    - kmod-openvswitch
    - kubeadm-1.15.12-0
    - kubectl-1.15.12-0
    - kubelet-1.15.12-0
    - kubernetes-cni
    - libaio
    - libusb
    - lvm2
    - nc
    - net-tools
    - ntp
    - ntpdate
    - oniguruma
    - openvswitch
    - pciutils
    - rsync
    - socat
    - spice
    - spice-protocol
    - sysstat
    - tcpdump
    - usbredir
    - wget
    - yunion-climc
    - yunion-executor
    - yunion-fetcherfs
    - yunion-ocadm
    - yunion-qemu-2.12.1
    - yunion-registry
  when:
  - is_centos_based is defined
  - non_iso_mode is defined

- name: config ntpd service
  template: src=ntp.conf dest=/etc/ntp.conf
  when: ntpd_server is defined

- name: sync with ntpd_server
  shell: |
    echo "sync with ntpd {{ ntpd_server }}"
    systemctl stop ntpd
    ntpdate {{ ntpd_server }}; echo $?
    echo "[PASS] sync with ntpd {{ ntpd_server }}"
  when: ntpd_server is defined
  args:
    warn: no
  ignore_errors: yes
  changed_when: false
  failed_when: false

- name: enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
  - "{{ common_services }}"
  when:
  - common_services is defined

- name: Stop/Disable Depreciated Services If Any
  shell: |
    for service in yunion-host-image yunion-host-sdnagent
    do
      if [ -f /usr/lib/systemd/system/$service.service ]; then
        systemctl stop $service
      fi
    done
  args:
    warn: no
