---
# This role contains common plays that will run on all nodes
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower | replace(' ', '_') }}-{{ ansible_distribution_major_version|lower|replace('/', '_') }}.{{ ansible_architecture }}.yml"
        - "{{ ansible_distribution|lower | replace(' ', '_') }}-{{ ansible_distribution_major_version|lower|replace('/', '_') }}.yml"
        - "{{ ansible_distribution|lower | replace(' ', '_') }}-{{ ansible_distribution_release|lower }}-{{ ansible_architecture }}.yml"
        - "{{ ansible_distribution|lower | replace(' ', '_') }}-{{ ansible_distribution_release|lower }}.yml"
        - "{{ ansible_distribution|lower | replace(' ', '_') }}-{{ ansible_distribution_major_version|lower|replace('/', '_') }}.yml"
        - "{{ ansible_distribution|lower | replace(' ', '_') }}-{{ ansible_architecture }}.yml"
        - "{{ ansible_distribution|lower | replace(' ', '_') }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_architecture }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../vars
  tags:
    - facts

- name: set offline/online deploy var
  set_fact:
    offline_deploy: "{{ lookup('env','OFFLINE_DATA_PATH') | length > 0 }}"
    offline_data_path: "{{ lookup('env', 'OFFLINE_DATA_PATH') }}"
    online_status: "{{ (lookup('env', 'OFFLINE_DATA_PATH') | length > 0) | ternary('offline', 'online') }}"

- name: will start {{ online_status | upper }} deploy
  shell: exit 0

- name: set default fact is_running_on_vm
  set_fact:
    is_running_on_vm: false

- name: detect if running on VM
  set_fact:
    is_running_on_vm: true
  when:
  - ansible_virtualization_type is defined
  - ansible_virtualization_type != ''
  - ansible_virtualization_type != 'NA'
  - ansible_virtualization_role | default("") != "host"

- name: join as host condition
  set_fact:
    join_as_host: false

- name: vm node join as host agent
  set_fact:
    join_as_host: true
  when:
  - k8s_node_as_oc_host|default(false)|bool == true
  - k8s_node_as_oc_host_on_vm | default(false)|bool == true
  - is_running_on_vm | default(false)|bool == true

- name: physical node join as host agent
  set_fact:
    join_as_host: true
  when:
  - k8s_node_as_oc_host|default(false)|bool == true
  - is_running_on_vm | default(false)|bool == false

- name: disable telegraf for host service
  include_role:
    name: utils/disable-telegraf-service
  when:
  - join_as_host | default(false)|bool == true
