---
- name: append packages to common_packages
  set_fact:
    common_packages: "{{ common_packages + extra_packages }}"
  when:
  - extra_packages is defined
  - common_packages is defined

- name: install common packages via loop
  package:
    name: "{{ item }}"
    disablerepo: "*"
    enablerepo: "yunion-*"
  with_items:
  - "{{ common_packages }}"
  when:
  - common_packages is defined
  async: 1200  # Maximum allowed time in Seconds
  poll: 0 # Polling Interval in Seconds
  register: package_install
  loop_control:
    index_var: item_index
    label: "[{{ item_index + 1 }}/{{ common_packages|length }}] {{ item }}"

- name: install latest packages via loop
  package:
    name: "{{ item }}"
    state: latest
    disablerepo: "*"
    enablerepo: "yunion-*"
  with_items:
  - "{{ latest_packages }}"
  retries: 6
  delay: 10
  register: latest_pkg_result
  until: latest_pkg_result.rc == 0
  ignore_errors: yes
  when:
  - latest_packages is defined

- name: install misc obsolete packages
  package: name="{{ item }}" disablerepo="*" enablerepo="yunion-*"
  with_items:
  - yunion-qemu-2.12.1
  when:
  - is_centos_x86 is defined

- name: Check that if selinux config exists
  stat:
    path: /etc/selinux/config
  register: selinux_conf_exists

- name: Turn off selinux
  selinux:
    state: disabled
  when:
    - selinux_conf_exists.stat.exists
