---
- name: append packages to common_packages
  set_fact:
    common_packages: "{{ common_packages + extra_packages }}"
  when:
  - extra_packages is defined
  - common_packages is defined

- name: install common packages via loop
  package:
    name: "{{ item }}"
    disablerepo: "{{ (online_status != 'online') | ternary('*', omit) }}"
    enablerepo: "{{ (online_status != 'online') | ternary('yunion-*', omit) }}"
  with_items:
  - "{{ common_packages }}"
  when:
  - common_packages is defined

- name: install latest packages via loop
  package:
    name: "{{ item }}"
    state: latest
    disablerepo: "{{ (online_status != 'online') | ternary('*', omit) }}"
    enablerepo: "{{ (online_status != 'online') | ternary('yunion-*', omit) }}"
  with_items:
  - "{{ latest_packages }}"
  when:
  - latest_packages is defined

- name: install misc obsolete packages
  package:
    name: "{{ item }}"
    disablerepo: "{{ (online_status != 'online') | ternary('*', omit) }}"
    enablerepo: "{{ (online_status != 'online') | ternary('yunion-*', omit) }}"
  with_items:
  - yunion-qemu-2.12.1
  when:
  - is_centos_x86 is defined

- name: Check that if selinux config exists
  stat:
    path: /etc/selinux/config
  register: selinux_conf_exists

- name: Turn off selinux
  selinux:
    state: disabled
  when:
    - selinux_conf_exists.stat.exists
    - is_kylin_arm64 | default(false) | bool == false
