---
- name: Check distribution and version
  set_fact:
    is_debian_11_or_later: true
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version | int >= 11

- name: Import task utils/unified_cgroup_hierarchy.yml
  include_tasks: utils/unified_cgroup_hierarchy.yml
  when:
  - is_debian_11_or_later| default(false)|bool == true

- name: get version tag
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: |
    /usr/bin/kubectl get OnecloudCluster -n onecloud -o jsonpath='{.items[0].spec.version}'
  args:
      executable: /bin/bash
  delegate_to: "{{ k8s_controlplane_host }}"
  register: k8s_version_tag
  ignore_errors: true
  failed_when: false
  when: k8s_controlplane_host is defined

- name: set onecloud_version if not provided
  set_fact:
    onecloud_version: "{{ k8s_version_tag.stdout }}"
  when:
  - onecloud_version is not defined
  - k8s_version_tag is defined
  - k8s_version_tag.rc == 0

- name: set var
  set_fact:
    onecloud_version_abbr: "{{ onecloud_version | regex_replace('[^0-9.]+') | regex_findall('^[0-9]+\\.[0-9]+') | join('')}}"

- name: Import task utils/config_iptables.yml
  include_tasks: utils/config_iptables.yml

- name: init apt cache for debian
  get_url:
    url: https://iso.yunion.cn/debian/{{ ansible_distribution_major_version }}/{{ onecloud_version_abbr }}/{{ ansible_architecture }}/yunion.gpg-key.asc
    dest: /tmp/yunion.gpg-key.asc
    validate_certs: no
  become: true

# https://iso.yunion.cn/debian/10/3.9/x86_64/
- name: apply debian sig key
  shell: |
    echo "deb [trusted=yes] https://iso.yunion.cn/debian/{{ ansible_distribution_major_version }}/{{ onecloud_version_abbr }}/{{ ansible_architecture }}/ ./" > /etc/apt/sources.list.d/yunion.list;
    apt-key add /tmp/yunion.gpg-key.asc;
    apt-get update -y;
    rm -f /tmp/yunion.gpg-key.asc
  become: true
  args:
    executable: /bin/bash

- name: update common packages for debian 11
  set_fact:
    common_packages: "{{ ['libcapstone4'] + common_packages }}"
  when:
  - is_debian_11_or_later| default(false)|bool == true

- name: install common packages via loop
  package:
    name: "{{ package_item }}"
  become: true
  with_items:
  - "{{ common_packages }}"
  loop_control:
    index_var: item_index
    label: "[{{ item_index + 1 }}/{{ common_packages|length }}] {{ package_item }}"
    loop_var: package_item
  tags:
  - package

- name: install latest packages via loop
  package:
    name: "{{ package_item }}"
    state: latest
  become: true
  with_items:
  - "{{ latest_packages }}"
  when:
  - latest_packages is defined
  loop_control:
    index_var: item_index
    label: "[{{ item_index + 1 }}/{{ latest_packages|length }}] {{ package_item }}"
    loop_var: package_item
  tags:
  - package

- name: Check that if selinux config exists
  stat:
    path: /etc/selinux/config
  register: selinux_conf_exists

- name: Turn off selinux
  selinux:
    state: disabled
  become: true
  when:
    - selinux_conf_exists.stat.exists

- name: Import task utils/fix_ovmf_path
  include_tasks: utils/fix_ovmf_path.yml
