---
# This role contains common plays that will run on all nodes
- name: Install yum utils
  yum: name={{ item }} state=latest
  with_items:
  - yum-utils
  - bash-completion
  - epel-release

- name: Add yunion rpm repository
  get_url:
    url: https://iso.yunion.cn/yumrepo-3.3/yunion.repo
    dest: /etc/yum.repos.d/yunion.repo
  become: yes

- name: Install yunion common packages
  yum:
    name: "{{ packages }}"
    disablerepo: "*"
    enablerepo: "yunion-*"
  vars:
    packages:
    - epel-release
    - libaio
    - jq
    - libusb
    - lvm2
    - nc
    - ntp
    - fetchclient
    - fuse
    - fuse-devel
    - fuse-libs
    - oniguruma
    - pciutils
    - spice
    - spice-protocol
    - sysstat
    - tcpdump
    - usbredir
    - yunion-qemu-2.12.1
    - yunion-ocadm
    - yunion-climc
    - yunion-executor-server
    - kernel-3.10.0-1062.4.3.el7.yn20191203
    - kernel-devel-3.10.0-1062.4.3.el7.yn20191203
    - kernel-headers-3.10.0-1062.4.3.el7.yn20191203
    - kmod-openvswitch
    - openvswitch
    - net-tools

- name: Turn off selinux
  selinux:
    state: disabled

- name: Gather service facts
  service_facts:

- name: Disable systemd services
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  when: "item + '.service' in ansible_facts.services"
  loop:
  - firewalld
  - NetworkManager

- name: Load br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: Load br_netfilter at boot
  copy:
    owner: root
    group: root
    mode: "0644"
    dest: /etc/modules-load.d/kubernetes.conf
    content:
      br_netfilter

- name: Change sysctl setting
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
  loop:
  - net.bridge.bridge-nf-call-iptables
  - net.bridge.bridge-nf-call-ip6tables
  - net.ipv4.ip_forward

- name: Change sysctl fs.inotify.max_user_watches
  sysctl:
    name: "fs.inotify.max_user_watches"
    value: "65536"
    state: present

- name: Change sysctl fs.inotify.max_user_instances
  sysctl:
    name: "fs.inotify.max_user_instances"
    value: "8192"
    state: present

#  https://github.com/kubernetes-retired/contrib/blob/master/ansible/roles/node/tasks/swapoff.yml
- name: Turn off swap mount
  mount:
    name: swap
    fstype: swap
    state: absent
- name: Turn off swap now
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Config ipvs
  copy:
    owner: root
    group: root
    mode: "0755"
    src: ipvs.modules
    dest: /etc/sysconfig/modules/ipvs.modules
- name: Load ipvs modules
  shell:
    /etc/sysconfig/modules/ipvs.modules

# docker
- block:
  - name: Install docker
    yum: name={{ item }} state=present
    with_items:
    - docker-ce-19.03.9
    - docker-ce-cli-19.03.9
    - containerd.io

  - name: Make /etc/docker dir
    shell: mkdir -p /etc/docker

  - name: Config docker file
    template: src=daemon.json.j2 dest=/etc/docker/daemon.json

  - name: Restart docker service
    service: name=docker state=restarted daemon_reload=yes enabled=yes
  when:
    skip_docker_config is not defined or skip_docker_config|default(false)|bool == false

# k8s packages
- name: Install k8s packages
  yum: name={{ item }} state=present
  with_items:
  - bridge-utils
  - ipvsadm
  - conntrack-tools
  - jq
  - kubelet-1.15.8-0
  - kubectl-1.15.8-0
  - kubeadm-1.15.8-0
  tags: k8s

- name: Enable kubelet
  service: name=kubelet enabled=yes
  tags: k8s

- name: Export yunion bin path in /etc/profile
  lineinfile:
    dest: /etc/profile
    line: "export PATH=$PATH:/opt/yunion/bin"
    state: present
    create: yes
    regexp: '^export PATH=.*/opt/yunion/bin'
  when: shell is undefined or shell == 'bash'

- name: Enable yunion systemd services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
  - yunion-executor
