---
- name: checking ports
  include_role:
    name: utils/misc-check

- name: Set facts
  set_fact:
    major_version_task_file: "{{ onecloud_major_version }}_{{ online_status }}.yml"

- name: Import task "{{ major_version_task_file }}"
  include_tasks: "{{ major_version_task_file }}"

# onecloud/roles/common/tasks/
- name: Import OS Arch tasks
  include_tasks: "{{ item }}"
  with_first_found:
  - files:
    - "{{ ansible_distribution | lower | regex_replace('[^a-zA-Z0-9 ]+|[ ]+$', '') | replace(' ','_') }}-{{ansible_distribution_release}}.yml"
    - "{{ ansible_distribution | lower |replace(' ', '_')}}_{{ ansible_distribution_major_version |lower }}_{{ ansible_architecture }}.yml"
    - "{{ ansible_distribution | lower |replace(' ', '_')}}_{{ ansible_distribution_major_version |lower }}.yml"
    - "{{ ansible_distribution | lower |replace(' ', '_')}}.yml"
    paths:
    - ../tasks

- name: reset iptables rules
  shell: |
    # backup iptable ruleset
    fn=/etc/iptables.backup.$(date +"%Y%m%d-%H%M%S")
    iptables-save > "$fn"

    # reset iptable rules
    iptables -t nat -F
    iptables -t nat -X
    iptables -t nat -P PREROUTING ACCEPT
    iptables -t nat -P POSTROUTING ACCEPT
    iptables -t nat -P OUTPUT ACCEPT
    iptables -t mangle -F
    iptables -t mangle -X
    iptables -t mangle -P PREROUTING ACCEPT
    iptables -t mangle -P INPUT ACCEPT
    iptables -t mangle -P FORWARD ACCEPT
    iptables -t mangle -P OUTPUT ACCEPT
    iptables -t mangle -P POSTROUTING ACCEPT
    iptables -F
    iptables -X
    iptables -P FORWARD ACCEPT
    iptables -P INPUT ACCEPT
    iptables -P OUTPUT ACCEPT
    iptables -t raw -F
    iptables -t raw -X
    iptables -t raw -P PREROUTING ACCEPT
    iptables -t raw -P OUTPUT ACCEPT
    service iptables save || :
    service iptables restart || :
  args:
    executable: /bin/bash

- name: Stop/Disable Depreciated Services If Any
  shell: |
    for service in yunion-host-image yunion-host-sdnagent firewalld
    do
      if [ -f /usr/lib/systemd/system/$service.service ]; then
        systemctl disable --now $service
      fi
    done
  args:
    executable: /bin/bash

- name: Config NetworkManager
  include_role:
    name: utils/config-network-manager

- name: Load br_netfilter
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
  - br_netfilter
  - ip_conntrack

- name: Load br_netfilter at boot
  copy:
    owner: root
    group: root
    mode: "0644"
    dest: /etc/modules-load.d/kubernetes.conf
    content:
      br_netfilter

- name: Change sysctl setting
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
  loop:
  - net.bridge.bridge-nf-call-iptables
  - net.bridge.bridge-nf-call-ip6tables
  - net.ipv4.ip_forward

- name: Change sysctl fs.inotify.max_user_watches
  sysctl:
    name: "fs.inotify.max_user_watches"
    value: "65536"
    state: present

- name: Change sysctl fs.inotify.max_user_instances
  sysctl:
    name: "fs.inotify.max_user_instances"
    value: "8192"
    state: present

- name: Disable systemd swap service
  shell: |
    dev=$(cat /proc/swaps |grep -v 'Filename' |wc -l)
    if [ "$dev" -eq 0 ]; then
      exit 0
    fi

    for i in $(systemctl --type swap --all|grep 'dev'|grep active |awk '{print $1}' ); do
        if [ -z "$i" ]; then
            continue
        fi
        systemctl stop "$i"
        systemctl mask "$i"
    done
    systemctl daemon-reload

    cp -fv /etc/fstab /etc/fstab.$(date +"%Y%m%d-%H%M%S").bak
    sed -i '/swap/ s/^#*/#/' -i /etc/fstab

  args:
    executable: /bin/bash
  when:
  - is_debian_based is defined

#  https://github.com/kubernetes-retired/contrib/blob/master/ansible/roles/node/tasks/swapoff.yml
- name: Turn off swap mount
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
  - swap
  - none

- name: Turn off swap now
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Create sysconfig directory if does not exist
  file:
    path: /etc/sysconfig/modules/
    state: directory
    mode: '0755'

- name: kernel module config
  include_role:
    name: utils/kernel-modules

# docker
- block:

  - name: Make /etc/docker dir
    file:
      path: /etc/docker
      state: directory
      owner: root
      group: root

  - name: Config docker file
    template: src=daemon.json.j2 dest=/etc/docker/daemon.json
    when: 
    - is_uos_kongzi|default(false) | bool == false 

  - name: Config docker file
    shell: |
      cat > /etc/docker/daemon.json <<EOF
      {
        "bridge": "none",
        "experimental": true,
        "iptables": false,
        "data-root": "/opt/docker"
      }
      EOF
    args:
      executable: /bin/bash
    when: 
    - is_uos_kongzi|default(false) | bool == true

  - name: Restart docker service
    service: name=docker state=restarted daemon_reload=yes enabled=yes
  when:
    skip_docker_config is not defined or skip_docker_config|default(false)|bool == false

# k8s packages
- name: Enable kubelet
  service: name=kubelet enabled=yes
  tags: k8s

- name: Export cloud bin path in /etc/profile
  lineinfile:
    dest: /etc/profile
    line: "export PATH=$PATH:/opt/yunion/bin"
    state: present
    create: yes
    regexp: '^export PATH=.*/opt/yunion/bin'
  when: shell is undefined or shell == 'bash'

- name: Enable cloud systemd services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
  - yunion-executor

- name: Include cronjobs
  include_role:
    name: utils/cronjobs
