---
- name: Add cloud rpm repository
  get_url:
    url: https://iso.yunion.cn/yumrepo-3.8/yunion.repo
    dest: /etc/yum.repos.d/yunion.repo
    validate_certs: no
  become: yes
  when:
  - is_centos_x86 is defined

- name: Install cloud common packages
  yum:
    state: latest
    enablerepo: "{{ (online_status != 'online') | ternary('yunion-*', omit) }}"
    disablerepo: "{{ (online_status != 'online') | ternary('*', omit) }}"
    name:
      - yunion-executor
  when:
  - is_centos_x86 is defined

- name: init apt cache for debian
  get_url:
    url: https://iso.yunion.cn/uos/buster/{{ debian_based_arch }}/3.8/yunion.gpg-key.asc
    dest: /tmp/yunion.gpg-key.asc
    validate_certs: no
  become: yes
  when:
  - is_debian_based is defined

- name: apply debian sig key
  shell: |
    apt-key add /tmp/yunion.gpg-key.asc;
    apt-get update -y;
    rm -f /tmp/yunion.gpg-key.asc
  args:
    executable: /bin/bash
  when:
  - is_debian_based is defined
