---
- name: Add cloud rpm repository
  get_url:
    url: https://iso.yunion.cn/centos/7/3.11/{{ansible_architecture}}/yunion.repo
    dest: /etc/yum.repos.d/yunion.repo
    validate_certs: no
  become: yes
  when:
  - is_centos_x86 | default(false) | bool == true or is_centos_aarch64 | default(false) | bool == true

- name: Add cloud rpm repository for Kylin
  get_url:
    url: https://iso.yunion.cn/kylin/v10-{{ansible_distribution_release|lower}}/3.11/{{ansible_architecture}}/kylin-yunion.repo
    dest: /etc/yum.repos.d/kylin-yunion.repo
    validate_certs: no
  become: yes
  when:
  - is_kylin_based|default(false)|bool == true

- name: make cache
  shell: |
    if [ -f /etc/yum.repos.d/yunion.repo ] || [ -f /etc/yum.repos.d/kylin-yunion.repo ]; then
      yum clean all
      yum makecache
    fi
  become: yes
  args:
    executable: /bin/bash
  when:
  - is_centos_based is defined

- name: install libselinux-python for arm64 centos
  yum:
    name: libselinux-python
  when:
  - is_centos_aarch64 is defined
  become: yes
