---
- name: Add cloud rpm repository for Kylin
  get_url:
    url: https://iso.yunion.cn/kylin/v10-{{ansible_distribution_release|lower}}/3.10/{{ansible_architecture}}/kylin-yunion.repo
    dest: /etc/yum.repos.d/kylin-yunion.repo
    validate_certs: no
  become: yes
  when:
  - is_kylin_based|default(false)|bool == true

- name: Add cloud rpm repository for OpenEuler
  get_url:
    url: https://iso.yunion.cn/openeuler/{{ansible_distribution_major_version |lower}}/3.10/{{ansible_architecture}}/yunion.repo
    dest: /etc/yum.repos.d/yunion-openeuler.repo
    validate_certs: no
  become: yes
  when:
  - is_openeuler_based|default(false)|bool == true

  when:
  - ansible_distribution in ['Anolis OS', 'Rocky']

- name: make cache
  shell: |
    yum clean all
    yum -y --disablerepo='*' --enablerepo='yunion*' makecache
  become: yes
  when:
  - is_centos_based is defined

