---
- name: Add yunion rpm repository
  get_url:
    url: https://iso.yunion.cn/yumrepo-3.7/yunion.repo
    dest: /etc/yum.repos.d/yunion.repo
    validate_certs: no
  become: yes
  when:
  - is_centos_x86 is defined
  - non_iso_mode is defined

- name: Install yunion common packages for centos x86
  yum:
    state: latest
    name:
      - kernel-3.10.0-1160.6.1.el7.yn20201125
      - kernel-devel-3.10.0-1160.6.1.el7.yn20201125
      - kernel-headers-3.10.0-1160.6.1.el7.yn20201125
      - yunion-executor
  when:
  - is_centos_x86 is defined
  - non_iso_mode is defined

- name: init apt cache for uos
  shell: |
    echo "deb [trusted=yes] https://iso.yunion.cn/uos/buster/{{ debian_based_arch }}/3.7 ./" > /etc/apt/sources.list.d/yunion.list;
    curl -k https://iso.yunion.cn/uos/buster/{{ debian_based_arch }}/3.7/yunion.gpg-key.asc -o yunion.gpg-key.asc;
    apt-key add yunion.gpg-key.asc;
    apt-get update -y;
    rm -f yunion.gpg-key.asc;
  args:
    executable: /bin/bash
  when:
  - is_debian_based is defined

- name: Add yunion rpm repository for arm64 centos
  get_url:
    url: https://iso.yunion.cn/centos-7-aarch/yunion.repo
    dest: /etc/yum.repos.d/yunion.repo
    validate_certs: no
  become: yes
  when:
  - is_centos_aarch64 is defined
  - non_iso_mode is defined

- name: Install yunion common packages for arm64
  yum:
    state: latest
    name:
      - kernel-4.14.0-115.8.2.el7a.yn20210924
      - kernel-devel-4.14.0-115.8.2.el7a.yn20210924
      - kernel-headers-4.14.0-115.8.2.el7a.yn20210924
      - yunion-executor-server
  when:
  - is_centos_aarch64 is defined
  - non_iso_mode is defined
