- name: Assert {{ ansible_distribution }} {{ ansible_distribution_version }} conditions
  assert:
    that:
    - "ansible_distribution_version is version('10', '>=')"
    - "ansible_distribution_version is version('12', '<')"

