- name: Check If {{ ansible_distribution }} {{ ansible_distribution_version }} Is Supported ({{ ansible_distribution|lower | replace(' ', '_') | replace('\"_', '') }}.yml)
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower | replace(' ', '_') | replace('\"_', '') }}.yml"
      skip: false
