- name: Install clickhouse services
  package:
    name: "{{ item }}"
    state: "present"
    disablerepo: "{{ (online_status != 'online') | ternary('*', omit) }}"
    enablerepo: "{{ (online_status != 'online') | ternary('yunion-*', omit) }}"
  become: yes
  with_items:
  - clickhouse-server
  - clickhouse-client
