---

- name: config iptables to legacy way
  shell: |
    if sudo iptables -V |grep -wq nf_tables; then
      sudo update-alternatives --install /usr/sbin/iptables iptables /usr/sbin/iptables-legacy 10
      sudo update-alternatives --install /usr/sbin/ip6tables ip6tables /usr/sbin/ip6tables-legacy 10
      sudo update-alternatives --install /usr/sbin/arptables arptables /usr/sbin/arptables-legacy 10
      sudo update-alternatives --install /usr/sbin/ebtables ebtables /usr/sbin/ebtables-legacy 10
      if [ -x /usr/sbin/nft ]; then
          sudo nft flush ruleset
      fi
    fi
  become: true
  args:
    executable: /bin/bash

- name: Enable powertool
  shell: |
    dnf config-manager --set-enabled -y PowerTools
  become: yes

# try to reuse following codes in redhat-family such as rocky8.
- name: Include RedHat General Repo Init
  include_tasks: redhat-general-repo.yml

- name: Enable {{ ansible_distribution }} Modules
  shell: dnf module enable -y "{{dnf_module}}"
  with_items:
  - "{{ dnf_modules }}"
  loop_control:
    index_var: item_index
    loop_var: dnf_module
  become: true
  when:
  - dnf_modules is defined

- name: Include RedHat Family Common Tasks
  include_tasks: redhat.yml
