- name: assert onecloud_version_abbr
  fail:
    msg: "onecloud_version_abbr is not defined."
  when:
  -  onecloud_version_abbr |default('') | length == 0
# TODO define onecloud_version_abbr globally

- name: Online repo
  shell: |
    cat > /etc/yum.repos.d/yunion.repo <<EOF_MISC
    [yunion-repo-base]
    name=Packages for Yunion Multi-Cloud Platform -
    baseurl=https://iso.yunion.cn/centos/7/{{onecloud_version_abbr}}/{{ansible_architecture}}
    sslverify=0
    failovermethod=priority
    enabled=1
    gpgcheck=0
    priority=1

    [yunion-repo-updates]
    name=Yunion Bin Packages for Yunion Multi-Cloud Platform -
    baseurl=https://iso.yunion.cn/rpm-updates/{{ansible_architecture}}
    sslverify=0
    failovermethod=priority
    enabled=1
    gpgcheck=0
    priority=2
    EOF_MISC
  become: yes
  args:
    executable: /bin/bash
  when:
  - online_status is defined
  - online_status == 'online'

- name: install misc obsolete packages
  package:
    name: "{{ package_item }}"
    disablerepo: "{{ (online_status != 'online') | ternary('*', omit) }}"
    enablerepo: "{{ (online_status != 'online') | ternary('yunion-*', omit) }}"
  become: yes
  loop_control:
    index_var: item_index
    loop_var: package_item
  with_items:
  - yunion-qemu-2.12.1
  when:
  - is_centos_x86 is defined
  tags:
  - package

- name: Include RedHat Family Common Tasks
  include_tasks: redhat.yml
