- name: install common packages via loop
  package:
    name: "{{ package_item }}"
  become: true
  with_items:
  - "{{ common_packages }}"
  loop_control:
    index_var: item_index
    label: "[{{ item_index + 1 }}/{{ common_packages|length }}] {{ package_item }}"
    loop_var: package_item
  tags:
  - package

- name: install latest packages via loop
  package:
    name: "{{ package_item }}"
    state: latest
  become: true
  with_items:
  - "{{ latest_packages }}"
  when:
  - latest_packages is defined
  loop_control:
    index_var: item_index
    label: "[{{ item_index + 1 }}/{{ latest_packages|length }}] {{ package_item }}"
    loop_var: package_item
  tags:
  - package

- name: Check that if selinux config exists
  stat:
    path: /etc/selinux/config
  register: selinux_conf_exists

- name: Turn off selinux
  selinux:
    state: disabled
  become: true
  when:
    - selinux_conf_exists.stat.exists

- name: Import task utils/fix_ovmf_path
  include_tasks: utils/fix_ovmf_path.yml
