---
- name: Check distribution and version
  set_fact:
    is_debian_11_or_later: true
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version | int >= 11

- name: update common packages for debian 11
  set_fact:
    common_packages: "{{ ['libcapstone4'] + common_packages }}"

- name: Include Debian Family Common Tasks
  include_tasks: debian_10.yml
