- name: enable repo
  shell: |
    cat > /etc/yum.repos.d/yunion.repo <<EOF_MISC
    [yunion-repo-base]
    name=Packages for Yunion Multi-Cloud Platform -
    baseurl=https://iso.yunion.cn/kylin/{{ ansible_distribution_version |lower }}-{{ ansible_distribution_release | lower }}/base/{{ ansible_architecture }}
    sslverify=0
    failovermethod=priority
    enabled=1
    gpgcheck=0

    [yunion-repo-updates]
    name=Yunion Bin Packages for Yunion Multi-Cloud Platform -
    baseurl=https://iso.yunion.cn/rpm-updates/{{ansible_architecture}}
    sslverify=0
    failovermethod=priority
    enabled=1
    gpgcheck=0
    EOF_MISC
  become: yes

- name: Update package list for {{ansible_distribution}} {{ansible_distribution_release}}
  set_fact:
    common_packages: "{{common_packages | difference(['docker-ce']) + ['docker']}}"
  when:
  - ansible_distribution_release == 'Lance'

- name: Include RedHat Family Common Tasks
  include_tasks: redhat.yml
