---

- name: enable repo
  shell: |
    cat > /etc/yum.repos.d/yunion.repo <<EOF_MISC
    [yunion-repo-base]
    name=Packages for Yunion Multi-Cloud Platform -
    baseurl=https://iso.yunion.cn/{{ ansible_distribution| replace(' ','') | lower }}/{{ ansible_distribution_version }}/base/{{ ansible_architecture }}
    sslverify=0
    failovermethod=priority
    enabled=1
    gpgcheck=0

    [yunion-repo-updates]
    name=Yunion Bin Packages for Yunion Multi-Cloud Platform -
    baseurl=https://iso.yunion.cn/rpm-updates/{{ansible_architecture}}
    sslverify=0
    failovermethod=priority
    enabled=1
    gpgcheck=0
    EOF_MISC
  become: yes

- name: Enable {{ ansible_distribution }} Modules
  shell: dnf module enable -y "{{dnf_module}}"
  with_items:
  - "{{ dnf_modules }}"
  loop_control:
    index_var: item_index
    loop_var: dnf_module
  become: true
  when:
  - dnf_modules is defined

- name: Include RedHat Family Common Tasks
  include_tasks: redhat.yml
