- name: Install mariadb
  package:
    name: "{{ item }}"
    state: "present"
  with_items:
    - mariadb-server
      #    - python3-pymysql

- name: python pip
  pip:
    name: PyMySQL

- name: Allow remote hosts to connect (Debian)
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    backrefs: yes
    regexp: '^bind-address'
    line: 'bind-address            = 0.0.0.0'
    state: present

- name: make conf dir
  file:
    name: /etc/my.cnf.d
    state: directory

# restart the mariadb service asap to allow remote access
- name: Restart Mariadb
  systemd:
    name: mariadb
    state: restarted
    enabled: yes

