- name: Install mysql python for Kylin
  package:
    name: "{{ item }}"
    state: installed
    disablerepo: "*"
    enablerepo: "yunion-*"
  with_items:
  - mariadb-server

- name: pips for mysql/mariadb
  pip:
    name: PyMySQL

- name: set fact for socket
  set_fact:
    login_unix_socket: /var/lib/mysql/mysql.sock
