- name: Install mysql python for Kylin
  package:
    name: "{{ item }}"
    state: installed
    disablerepo: "{{ disablerepo }}"
    enablerepo: "{{ enablerepo }}"
  with_items:
  - mariadb-server

- name: pips for mysql/mariadb
  pip:
    name: PyMySQL
