- name: Install mysql python for Kylin
  package:
    name: "{{ item }}"
    state: installed
    disablerepo: "{{ (online_status != 'online') | ternary('*', omit) }}"
    enablerepo: "{{ (online_status != 'online') | ternary('yunion-*', omit) }}"
  with_items:
  - mariadb-server

- name: pips for mysql/mariadb
  pip:
    name: PyMySQL
