- name: Import Install mariadb task
  include_tasks: "{{ ansible_distribution | lower | replace(' ', '_')}}-{{ ansible_architecture }}.yml"

- name: Copy my.cnf
  copy:
    src: my.cnf
    dest: /etc/my.cnf
    backup: yes

- name: enable and start mariadb
  systemd:
    name: mariadb
    enabled: yes
    state: started

- name: Change root password
  mysql_user:
    login_user: "{{ db_user }}"
    login_port: "{{ db_port | default(3306) }}"
    login_password: "{{ db_password }}"
    password: "{{ db_password }}"
    name: "{{ db_user }}"
    priv: '*.*:ALL,GRANT'
    host: "{{ item }}"
    check_implicit_admin: true
  loop:
    - "{{ db_host }}"
    - "localhost"
    - "%"
    - "::1"
    - "127.0.0.1"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  when:
    - is_redhat_based |default(false)|bool == true

- name: Change root password for debian
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: "{{ db_user }}"
    login_port: "{{ db_port | default(3306) }}"
    login_password: "{{ db_password }}"
    password: "{{ db_password }}"
    name: "{{ db_user }}"
    priv: '*.*:ALL,GRANT'
    host: "{{ item }}"
    check_implicit_admin: true
  loop:
    - "{{ db_host }}"
    - "localhost"
    - "%"
    - "::1"
    - "127.0.0.1"
  when:
    - is_debian_based |default(false)|bool == true
  vars:
    ansible_python_interpreter: /usr/bin/python3
