# ./onecloud/roles/mariadb/tasks/
- name: Import Install mariadb task
  include_tasks: "{{ ansible_distribution | lower | replace(' ', '_')}}-{{ ansible_architecture }}.yml"

- name: Copy my.cnf
  copy:
    src: my.cnf
    dest: /etc/my.cnf
    backup: yes

- name: enable and start mariadb
  systemd:
    name: mariadb
    enabled: yes
    state: started

- name: Change root password
  mysql_user:
    login_unix_socket: "{{ login_unix_socket }}"
    login_user: "{{ db_user }}"
    login_port: "{{ db_port | default(3306) }}"
    login_password: "{{ db_password }}"
    password: "{{ db_password }}"
    name: "{{ db_user }}"
    priv: "*.*:ALL,GRANT"
    host: "{{ item }}"
    check_implicit_admin: true
  loop:
    - "{{ db_host }}"
    - "%"
    - "::1"
    - "127.0.0.1"
    - "localhost"
  vars:
    ansible_python_interpreter: /usr/bin/python3

# https://dba.stackexchange.com/questions/102066/ansible-how-to-change-mysql-server-root-password-by-reprovisioning-the-server
- name: Create .my.cnf
  template:
   src: "/home/ch/ocboot/templates/mariadb/client.my.cnf.j2"
   dest: "/root/.my.cnf"
   owner: root
   group: root
   mode: 0600

# https://stackoverflow.com/questions/38433295/unable-to-change-password-for-root-account-ansible
#  - name: Create .my.cnf file with root password credentials
#      become: yes
#      template: src=".my.cnf.j2" dest="/root/.my.cnf" owner=root group=root mode=0600
