- name: Install mariadb
  package:
    name: "{{ package_item }}"
    state: "present"
    disablerepo: "{{ (online_status != 'online') | ternary('*', omit) }}"
    enablerepo: "{{ (online_status != 'online') | ternary('yunion-*', omit) }}"
  with_items:
    - mariadb-server
  loop_control:
    loop_var: package_item

- name: pips for mysql/mariadb online
  pip:
    name: PyMySQL
  vars:
    ansible_python_interpreter: /usr/bin/python3
  when:
  - online_status == "online"

- name: pips for mysql/mariadb offline
  pip:
    name: PyMySQL
    extra_args: "--no-index --find-links=file://{{ offline_data_path }}/pips"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  when:
  - online_status == "offline"
  - offline_data_path is defined
  - offline_data_path | length > 0

- name: set fact for socket
  set_fact:
    login_unix_socket: /var/lib/mysql/mysql.sock
