---
# This role modifies tcp net ipv4 configuration
# only for primary and controlplane


- name: tcp_retries2
  sysctl:
    name: net.ipv4.tcp_retries2
    value: "7"
    reload: yes
    state: present
  become: true

- name: keepalive time
  sysctl:
    name: net.ipv4.tcp_keepalive_time
    value: "13"
    reload: yes
    state: present
  become: true

- name: keepalive intvl
  sysctl:
    name: net.ipv4.tcp_keepalive_intvl
    value: "7"
    reload: yes
    state: present
  become: true

- name: keepalive probes
  sysctl:
    name: net.ipv4.tcp_keepalive_probes
    value: "3"
    reload: yes
    state: present
  become: true

- name: net ipv4 neigh default gc_thresh 1
  sysctl:
    name: net.ipv4.neigh.default.gc_thresh1
    value: "1024"
    reload: yes
    state: present
  become: true

- name: net ipv4 neigh default gc_thresh 2
  sysctl:
    name: net.ipv4.neigh.default.gc_thresh2
    value: "4096"
    reload: yes
    state: present
  become: true

- name: net ipv4 neigh default gc_thresh 3
  sysctl:
    name: net.ipv4.neigh.default.gc_thresh3
    value: "8192"
    reload: yes
    state: present
  become: true
