- name: hello
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
    HOSTS: "/root/yunion-hosts"
  shell: |
    # "获取节点名称和IP"
    kubectl get nodes -o wide  | awk ' NR>1  {print $1,$6}' > /root/yunion-hosts2

    # 获取ansible IP
    kubectl get nodes -o wide  | awk ' NR>1  {print $6}' > /root/yunion-hosts
    cat /root/yunion-hosts

    # 查看yunion-qemu版本
    rpm -qa | grep yunion-qemu

    # 查看CPU 5分钟平均使用率
    top -b -n 1 | grep -oE 'load average:.*' | awk '{print $4}'

    echo -e "n查看内存使用率"
    free | grep Mem | awk '{printf "%.0f%%\n",$3/$2*100}'

    echo -e "n查看系统盘使用率"
    df -hT | grep dev

    echo -e "n查看数据盘使用率"
    df -h | grep '^/dev/.*/opt' || echo 没有单独挂载数据盘

    echo -e "n查看系统盘IO"
    iostat -x 1 10 | grep `df -h | grep '^/dev/.*/$' | awk -F'[/ ]' '{print $3}' | tr -d '[:digit:]'` |awk '{sum+=$NF} END {printf "%.0f%%" ,sum/NR}'

    echo -e "n查看数据盘IO"
    iostat -x 1 10 | grep `df -h | grep '^/dev/.*/opt' | awk -F'[/ ]' '{print $3}' | tr -d '[:digit:]'` |awk '{sum+=$NF} END {printf "%.0f%%" ,sum/NR}' ||echo '没有单独挂载数据盘'

  args:
    executable: /bin/bash
