---
- name: ensure routine inspection directory exists
  file:
    path: /opt/yunion/scripts/tools/
    state: directory

- name: copy routine inspection file
  copy:
    src: inspect.sh
    dest: /opt/yunion/scripts/tools/routine_check.sh
    owner: root
    group: root
    mode: 0755

- name: add host key
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: |
    source ~/.onecloud_rcadmin
    /opt/yunion/bin/climc-ee sshkeypair-show |grep '^ssh-rsa' >> /root/.ssh/authorized_keys && chmod 600 /root/.ssh/authorized_keys
  args:
    executable: /bin/bash
