---
- name: collect upgrade info
  import_tasks: collect_upgrade_info.yml

- name: Include cronjobs
  include_role:
    name: utils/cronjobs

- name: Include utils/k8s/kubelet/extra-args tasks
  include_role:
    name: utils/k8s/kubelet/extra-args

- name: Mkdir for offline upgrade
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ offline_data_path }}/repodata/"
    - "{{ offline_data_path }}/rpms/"
  when:
  - offline_data_path is defined
  - offline_data_path | length > 0

- name: common upgrade | Import major version upgrade task
  include_tasks: "{{ item }}"
  with_first_found:
  - files:
    - "{{ major_upgrade_task_file }}"
    - "{{lookup('ansible.builtin.fileglob', '*' + upgrade_onecloud_major_version + '.yml')}}"
    skip: true
  when:
    - is_major_upgrade or force_upgrade | default(false) | bool == true

- name: checking ports
  include_role:
    name: utils/kernel-modules
