---
- name: collect upgrade info
  import_tasks: collect_upgrade_info.yml

- name: Include cronjobs
  include_role:
    name: utils/cronjobs

- name: Include utils/k8s/kubelet/extra-args tasks
  include_role:
    name: utils/k8s/kubelet/extra-args

- name: common upgrade | Import major version upgrade task
  include_tasks: "{{ major_upgrade_task_file }}"
  when:
    - is_major_upgrade

- name: checking ports
  include_role:
    name: utils/kernel-modules
