---
- name: Setup repo mirrors
  include_role:
    name: utils/mirror

- name: "Add cloud rpm repository {{ yunion_yum_repo }}"
  get_url:
    url: "{{ yunion_yum_repo }}"
    dest: /etc/yum.repos.d/yunion.repo
    force: yes
    validate_certs: no
  become: yes
  when:
  - is_centos_x86 is defined

- name: Remove the old executor-server package
  yum:
    name: yunion-executor-server
    state: absent
  when:
  - is_centos_x86 is defined

- name: Upgrade common packages
  yum:
    name:
      - yunion-ocadm
      - yunion-climc
      - yunion-executor
    state: latest
    disablerepo: "{{ (online_status != 'online') | ternary('*', omit) }}"
    enablerepo: "{{ (online_status != 'online') | ternary('yunion-*', omit) }}"
  when:
  - is_centos_x86 is defined

- name: Restart executor service
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  loop:
    - yunion-executor
