---
- name: Setup repo mirrors
  include_role:
    name: utils/mirror

- name: "Add cloud rpm repository {{ yunion_yum_repo }}"
  get_url:
    url: "{{ yunion_yum_repo }}"
    dest: /etc/yum.repos.d/yunion.repo
    force: yes
    validate_certs: no
  become: yes
  when:
  - is_centos_x86 is defined

- name: "update repo"
  shell: |
    yum clean all
    yum --disablerepo='*' --enablerepo='yunion*' makecache fast
  when:
  - is_centos_x86 is defined

- name: "uninstall old rpms"
  shell: |
    rpms=$(rpm -qa |grep yunion|grep -v fetcherfs |grep 3.6| xargs)
    if [ -n "$rpms" ]; then
      yum remove -y $rpms
    fi
  when:
  - is_centos_x86 is defined
  args:
    executable: /bin/bash

- name: Upgrade common packages
  yum:
    name:
      - yunion-ocadm
      - yunion-climc
      - yunion-executor
      - kernel-3.10.0-1160.6.1.el7.yn20201125
      - kernel-devel-3.10.0-1160.6.1.el7.yn20201125
      - kernel-headers-3.10.0-1160.6.1.el7.yn20201125
    disablerepo: "{{ (online_status != 'online') | ternary('*', omit) }}"
    enablerepo: "{{ (online_status != 'online') | ternary('yunion-*', omit) }}"
    state: latest
  when:
  - is_centos_x86 is defined
