---
- name: Setup repo mirrors
  include_role:
    name: utils/mirror

- name: "Add cloud rpm repository {{ yunion_yum_repo }}"
  copy:
    content: |
      [yunion-repo-offline]
      name=Packages for Yunion Multi-Cloud Platform -
      baseurl=https://iso.yunion.cn/$contentdir/$releasever/3.8/$basearch
      sslverify=0
      failovermethod=priority
      enabled=1
      gpgcheck=0
    dest: /etc/yum.repos.d/yunion.repo
  become: yes
  retries: 3
  delay: 30
  when:
  - is_centos | default(false) | bool == true
  - offline_data_path is not defined or offline_data_path | length == 0

- name: "update repo"
  shell: |
    yum clean all
    yum --disablerepo='*' --enablerepo='yunion*' makecache fast
  when:
  - is_centos_based is defined

- name: "uninstall old rpms"
  shell: |
    rpms=$(rpm -qa |grep yunion|grep -v fetcherfs |grep 3.6| xargs)
    if [ -n "$rpms" ]; then
      yum remove -y $rpms
    fi
  when:
  - is_centos_based is defined
  args:
    executable: /bin/bash

- name: Install ceph-common packages
  yum:
    name:
      - ceph-common
    state: latest
  when:
  - is_centos_based is defined

- name: Upgrade common packages
  yum:
    name:
      - yunion-ocadm
      - yunion-climc
      - yunion-executor
    disablerepo: "{{ (online_status != 'online') | ternary('*', omit) }}"
    enablerepo: "{{ (online_status != 'online') | ternary('yunion-*', omit) }}"
    state: latest
  when:
  - is_centos_based is defined
