---
- name: Setup repo mirrors
  include_role:
    name: utils/mirror

- name: "Add cloud rpm repository {{ yunion_yum_repo }}"
  get_url:
    url: "{{ yunion_yum_repo }}"
    dest: /etc/yum.repos.d/yunion.repo
    force: yes
    validate_certs: no
  become: yes
  when:
  - is_centos_x86 is defined

- name: "update repo"
  shell: |
    yum clean all
    yum --disablerepo='*' --enablerepo='yunion*' makecache fast
  when:
  - is_centos_based is defined

- name: "uninstall old rpms"
  shell: |
    rpms=$(rpm -qa |grep yunion|grep -v fetcherfs |grep 3.6| xargs)
    if [ -n "$rpms" ]; then
      yum remove -y $rpms
    fi
  when:
  - is_centos_based is defined
  args:
    executable: /bin/bash

- name: Install ceph-common packages
  yum:
    name:
      - ceph-common
    state: latest
  when:
  - is_centos_based is defined

- name: Upgrade common packages
  yum:
    name:
      - yunion-ocadm
      - yunion-climc
      - yunion-executor
    disablerepo: "{{ disablerepo }}"
    enablerepo: "{{ enablerepo }}"
    state: latest
  when:
  - is_centos_based is defined
