---
- name: Ensure a job that runs every minute
  cron:
    name: "Remove unused dangling docker images"
    special_time: daily
    user: root
    job: "/usr/bin/docker image prune -f"
    cron_file: yunion_docker_image_prune
  become: true

- name: ensure /opt/yunion/scripts path exists
  file:
    path: /opt/yunion/scripts
    state: directory
  become: true

- name: enable auto backup
  include_role:
    name: utils/auto-backup-services
  when:
  - offline_data_path | length > 0
