
- name: Reload NetworkManager
  service:
    name: NetworkManager
    state: reloaded
  when: '"running" in nm_check.stdout'
  notify:
    - Remove immutable flag on /etc/resolv.conf

- name: Remove immutable flag on /etc/resolv.conf
  shell: |
    chattr -i /etc/resolv.conf
  ignore_errors: yes

