debian_based_arch: amd64
is_debian_based: true
is_uos: true

common_packages:
  - apt-transport-https
  - bash-completion
  - bridge-utils
  - ceph-common
  - chntpw
  - conntrack
  - conntrackd
  - curl
  - dkms
  - docker-ce         #
  - git
  - glusterfs-common
  - gnupg-agent
  - gnupg2
  - ipset
  - ipvsadm
  - jq
  - kubeadm=1.15.12-00 #
  - kubectl=1.15.12-00 #
  - kubelet=1.15.12-00 #
  - librbd1
  - libspice-server1
  - libusb-1.0-0
  - libusbredirparser1
  - nfs-common
  - ntp
  - openvswitch-switch
  - ovmf
  - parallel
  - python-pymysql
  - python-selinux
  - python-yaml
  - python3-pip
  - software-properties-common
  - wget
  - "{{ yunion_qemu_package }}"

common_services:
  - ntp
  - yunion-executor

latest_packages:
    - ca-certificates
    - yunion-climc
    - yunion-executor
    - yunion-fetcherfs
    - yunion-ocadm
