- block:

  - name: generate clickhouse spec conf
    template:
      src: clickhouse.spec.j2
      dest: /tmp/clickhouse.spec.yaml

  - name: Apply modifications for clickhouse
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
    shell: |
      kubectl patch onecloudclusters -n onecloud default --patch "$(cat /tmp/clickhouse.spec.yaml)" --type merge && rm -f /tmp/clickhouse.spec.yaml
      for i in cloudevent glance keystone region kubeserver logger meter monitor notify webconsole
      do
        kubectl delete configmap -n onecloud default-$i
        kubectl rollout restart deployment -n onecloud  default-$i
      done
    args:
      executable: /bin/bash

  when:
  - offline_data_path is defined
  - offline_data_path | length > 0
  - is_centos_x86 is defined && is_centos_x86 == true
