- name: Install registry
  yum:
    name: "{{ item }}"
    disablerepo: "{{ (online_status != 'online') | ternary('*', omit) }}"
    enablerepo: "{{ (online_status != 'online') | ternary('yunion-*', omit) }}"
    state: present
  with_items:
  - yunion-registry
  when:
  - is_redhat_based is defined

- name: Create cloud conf directory
  file:
    name: /etc/yunion/
    state: directory

- name: Config registry
  template: src=registry.yml dest=/etc/yunion/registry.yml
  notify: restart registry

- name: Start registry service
  service: name=yunion-registry state=started enabled=yes
