# This role contains common plays that will run on all nodes

- name: Install Cloud Kernel
  yum:
    enablerepo: "{{ (online_status != 'online') | ternary('yunion-*', omit) }}"
    disablerepo: "{{ (online_status != 'online') | ternary('*', omit) }}"
    name:
    - kernel-5.4.130-1.yn20230805.el7
    - kernel-devel-5.4.130-1.yn20230805.el7
    - kernel-headers-5.4.130-1.yn20230805.el7
  become: yes
