- name: Install Cloud Kernel
  yum:
    disablerepo: "{{ (online_status != 'online') | ternary('*', omit) }}"
    enablerepo: "{{ (online_status != 'online') | ternary('yunion-*', omit) }}"
    name:
      - kernel-5.4.199-200.yn20221212.el7
