- hosts: mariadb_node
  roles:
    - mariadb

- hosts: registry_node
  roles:
    - registry

- hosts: primary_master_node
  roles:
    - primary-master-node/setup_k8s

- hosts: master_nodes
  roles:
    - master-node

- hosts: primary_master_node
  roles:
    - primary-master-node/setup_cloud

- hosts: worker_nodes
  roles:
    - worker-node

- hosts: primary_master_node
  roles:
    - primary-master-node/reboot
